jnmmes/ServiceCenter.Client/ServiceCenter.Client.Cell.Mvc/Areas/FMM/Models/ScheduleMonthViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using ServiceCenter.MES.Service.Client;
using ServiceCenter.Model;
using ServiceCenter.MES.Model.FMM;
using FMMResources = ServiceCenter.Client.Mvc.Resources.FMM;
using ServiceCenter.Client.Mvc.Resources;
using ServiceCenter.MES.Service.Client.FMM;
using System.Web.Mvc;
using ServiceCenter.Common;

namespace ServiceCenter.Client.Mvc.Areas.FMM.Models
{
    public class ScheduleMonthQueryViewModel
    {
        public ScheduleMonthQueryViewModel()
        {

        }

        [Display(Name = "ScheduleMonthQueryViewModel_LocationName", ResourceType = typeof(FMMResources.StringResource))]
        public string LocationName { get; set; }
        [Display(Name = "ScheduleMonthQueryViewModel_RouteOperationName", ResourceType = typeof(FMMResources.StringResource))]
        public string RouteOperationName { get; set; }
        [Display(Name = "ScheduleMonthQueryViewModel_Year", ResourceType = typeof(FMMResources.StringResource))]
        public string Year { get; set; }
        [Display(Name = "ScheduleMonthQueryViewModel_Month", ResourceType = typeof(FMMResources.StringResource))]
        public string Month { get; set; }

        public IEnumerable<SelectListItem> GetLocationName()
        {
            using (LocationServiceClient client = new LocationServiceClient())
            {
                PagingConfig cfg = new PagingConfig()
                {
                    IsPaging = false,
                    Where = string.Format("Level='{0}'", Convert.ToInt32(LocationLevel.Room))
                };

                MethodReturnResult<IList<Location>> result = client.Get(ref cfg);
                if (result.Code <= 0)
                {
                    IEnumerable<SelectListItem> lst = from item in result.Data
                                                      select new SelectListItem()
                                                      {
                                                          Text = item.Key,
                                                          Value = item.Key
                                                      };
                    return lst;
                }
            }
            return new List<SelectListItem>();
        }

        public IEnumerable<SelectListItem> GetRouteOperationName()
        {
            using (RouteOperationServiceClient client = new RouteOperationServiceClient())
            {
                PagingConfig cfg = new PagingConfig()
                {
                    IsPaging = false
                };

                MethodReturnResult<IList<RouteOperation>> result = client.Get(ref cfg);
                if (result.Code <= 0)
                {
                    IEnumerable<SelectListItem> lst = from item in result.Data
                                                      select new SelectListItem()
                                                      {
                                                          Text = item.Key,
                                                          Value = item.Key
                                                      };
                    return lst;
                }
            }
            return new List<SelectListItem>();
        }
    }

    public class ScheduleMonthViewModel
    {
        public ScheduleMonthViewModel()
        {
            this.CreateTime = DateTime.Now;
            this.EditTime = DateTime.Now;

        }

        [Required]
        [Display(Name = "ScheduleMonthViewModel_LocationName", ResourceType = typeof(FMMResources.StringResource))]
        [StringLength(50, MinimumLength = 1
                        , ErrorMessageResourceName = "ValidateStringLength"
                        , ErrorMessageResourceType = typeof(StringResource))]
        public string LocationName { get; set; }

        [Required]
        [Display(Name = "ScheduleMonthViewModel_RouteOperationName", ResourceType = typeof(FMMResources.StringResource))]
        [StringLength(50, MinimumLength = 1
                        , ErrorMessageResourceName = "ValidateStringLength"
                        , ErrorMessageResourceType = typeof(StringResource))]
        public string RouteOperationName { get; set; }

        [Required]
        [Display(Name = "ScheduleMonthViewModel_Year", ResourceType = typeof(FMMResources.StringResource))]
        public string Year { get; set; }
        [Required]
        [Display(Name = "ScheduleMonthViewModel_Month", ResourceType = typeof(FMMResources.StringResource))]
        public string Month { get; set; }

        [Required]
        [Display(Name = "ScheduleMonthViewModel_ScheduleName", ResourceType = typeof(FMMResources.StringResource))]
        [StringLength(50, MinimumLength = 1
                        , ErrorMessageResourceName = "ValidateStringLength"
                        , ErrorMessageResourceType = typeof(StringResource))]
        public string ScheduleName { get; set; }

        [Display(Name = "Editor", ResourceType = typeof(StringResource))]
        public string Editor { get; set; }


        [Display(Name = "EditTime", ResourceType = typeof(StringResource))]
        public DateTime? EditTime { get; set; }


        [Display(Name = "Creator", ResourceType = typeof(StringResource))]
        public string Creator { get; set; }


        [Display(Name = "CreateTime", ResourceType = typeof(StringResource))]
        public DateTime? CreateTime { get; set; }

        public IEnumerable<SelectListItem> GetLocationName()
        {
            using (LocationServiceClient client = new LocationServiceClient())
            {
                PagingConfig cfg = new PagingConfig()
                {
                    IsPaging = false,
                    Where = string.Format("Level='{0}'", Convert.ToInt32(LocationLevel.Room))
                };

                MethodReturnResult<IList<Location>> result = client.Get(ref cfg);
                if (result.Code <= 0)
                {
                    IEnumerable<SelectListItem> lst = from item in result.Data
                                                      select new SelectListItem()
                                                      {
                                                          Text = item.Key,
                                                          Value = item.Key
                                                      };
                    return lst;
                }
            }
            return new List<SelectListItem>();
        }

        public IEnumerable<SelectListItem> GetRouteOperationName()
        {
            using (RouteOperationServiceClient client = new RouteOperationServiceClient())
            {
                PagingConfig cfg = new PagingConfig()
                {
                    IsPaging = false
                };

                MethodReturnResult<IList<RouteOperation>> result = client.Get(ref cfg);
                if (result.Code <= 0)
                {
                    IEnumerable<SelectListItem> lst = from item in result.Data
                                                      select new SelectListItem()
                                                      {
                                                          Text = item.Key,
                                                          Value = item.Key
                                                      };
                    return lst;
                }
            }
            return new List<SelectListItem>();
        }

        public IEnumerable<SelectListItem> GetScheduleName()
        {
            using (ScheduleServiceClient client = new ScheduleServiceClient())
            {
                PagingConfig cfg = new PagingConfig()
                {
                    IsPaging = false
                };

                MethodReturnResult<IList<Schedule>> result = client.Get(ref cfg);
                if (result.Code <= 0)
                {
                    IEnumerable<SelectListItem> lst = from item in result.Data
                                                      select new SelectListItem()
                                                      {
                                                          Text = item.Key,
                                                          Value = item.Key
                                                      };
                    return lst;
                }
            }
            return new List<SelectListItem>();
        }

        public IEnumerable<SelectListItem> GetYear()
        {
            List<SelectListItem> lst= new List<SelectListItem>();
            int startYear = DateTime.Now.Year;
            for(int i=0;i<5;i++)
            {
                string value = Convert.ToString(startYear + i);
                lst.Add(new SelectListItem()
                        {
                            Text = value,
                            Value = value
                        });
            }
            return lst;
        }

        public IEnumerable<SelectListItem> GetMonth()
        {
            List<SelectListItem> lst = new List<SelectListItem>();
            for (int i = 1; i <= 12; i++)
            {
                string value = i.ToString("00");
                lst.Add(new SelectListItem()
                {
                    Text = value,
                    Value = value
                });
            }
            return lst;
        }
    }
}

jnmmes/ServiceCenter.Client/ServiceCenter.Client.Cell.Mvc/Areas/FMM/Controllers/ScheduleMonthController.cs
using ServiceCenter.Client.Mvc.Areas.FMM.Models;
using FMMResources = ServiceCenter.Client.Mvc.Resources.FMM;
using ServiceCenter.MES.Model.FMM;
using ServiceCenter.MES.Service.Client.FMM;
using ServiceCenter.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ServiceCenter.Client.Mvc.Areas.FMM.Controllers
{
    public class ScheduleMonthController : Controller
    {

        //
        // GET: /FMM/ScheduleMonth/
        public async Task<ActionResult> Index()
        {
            using (ScheduleMonthServiceClient client = new ScheduleMonthServiceClient())
            {
                await Task.Run(() =>
                {
                    PagingConfig cfg = new PagingConfig()
                    {
                        OrderBy = "Key"
                    };
                    MethodReturnResult<IList<ScheduleMonth>> result = client.Get(ref cfg);

                    if (result.Code == 0)
                    {
                        ViewBag.PagingConfig = cfg;
                        ViewBag.List = result.Data;
                    }
                });
            }
            return View(new ScheduleMonthQueryViewModel());
        }

        //
        //POST: /FMM/ScheduleMonth/Query
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Query(ScheduleMonthQueryViewModel model)
        {
            if (ModelState.IsValid)
            {
                using (ScheduleMonthServiceClient client = new ScheduleMonthServiceClient())
                {
                    await Task.Run(() =>
                    {
                        StringBuilder where = new StringBuilder();
                        if (model != null)
                        {
                            if (!string.IsNullOrEmpty(model.LocationName))
                            {
                                where.AppendFormat(" {0} Key.LocationName LIKE '{1}%'"
                                                    , where.Length > 0 ? "AND" : string.Empty
                                                    , model.LocationName);
                            }
                            if (!string.IsNullOrEmpty(model.RouteOperationName))
                            {
                                where.AppendFormat(" {0} Key.RouteOperationName LIKE '{1}%'"
                                                    , where.Length > 0 ? "AND" : string.Empty
                                                    , model.RouteOperationName);
                            }
                            if (!string.IsNullOrEmpty(model.Year))
                            {
                                where.AppendFormat(" {0} Key.Year LIKE '{1}%'"
                                                    , where.Length > 0 ? "AND" : string.Empty
                                                    , model.Year);
                            }
                            if (!string.IsNullOrEmpty(model.Month))
                            {
                                where.AppendFormat(" {0} Key.Month LIKE '{1}%'"
                                                    , where.Length > 0 ? "AND" : string.Empty
                                                    , model.Month);
                            }
                        }
                        PagingConfig cfg = new PagingConfig()
                        {
                            OrderBy = "Key",
                            Where = where.ToString()
                        };
                        MethodReturnResult<IList<ScheduleMonth>> result = client.Get(ref cfg);

                        if (result.Code == 0)
                        {
                            ViewBag.PagingConfig = cfg;
                            ViewBag.List = result.Data;
                        }
                    });
                }
            }
            return PartialView("_ListPartial");
        }
        //
        //POST: /FMM/ScheduleMonth/PagingQuery
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> PagingQuery(string where, string orderBy, int? currentPageNo, int? currentPageSize)
        {
            if (ModelState.IsValid)
            {
                int pageNo = currentPageNo ?? 0;
                int pageSize = currentPageSize ?? 20;
                if (Request["PageNo"] != null)
                {
                    pageNo = Convert.ToInt32(Request["PageNo"]);
                }
                if (Request["PageSize"] != null)
                {
                    pageSize = Convert.ToInt32(Request["PageSize"]);
                }

                using (ScheduleMonthServiceClient client = new ScheduleMonthServiceClient())
                {
                    await Task.Run(() =>
                    {
                        PagingConfig cfg = new PagingConfig()
                        {
                            PageNo = pageNo,
                            PageSize = pageSize,
                            Where = where ?? string.Empty,
                            OrderBy = orderBy ?? string.Empty
                        };
                        MethodReturnResult<IList<ScheduleMonth>> result = client.Get(ref cfg);
                        if (result.Code == 0)
                        {
                            ViewBag.PagingConfig = cfg;
                            ViewBag.List = result.Data;
                        }
                    });
                }
            }
            return PartialView("_ListPartial");
        }
        //
        // POST: /FMM/ScheduleMonth/Save
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Save(ScheduleMonthViewModel model)
        {
            using (ScheduleMonthServiceClient client = new ScheduleMonthServiceClient())
            {
                ScheduleMonth obj = new ScheduleMonth()
                {
                    Key = new ScheduleMonthKey()
                    {
                        LocationName=model.LocationName,
                        RouteOperationName=model.RouteOperationName,
                        Year=model.Year,
                        Month=model.Month
                    },
                    ScheduleName=model.ScheduleName,
                    Editor = User.Identity.Name,
                    EditTime = DateTime.Now,
                    CreateTime = DateTime.Now,
                    Creator = User.Identity.Name
                };
                MethodReturnResult rst = await client.AddAsync(obj);
                if (rst.Code == 0)
                {
                    rst.Message = string.Format(FMMResources.StringResource.ScheduleMonth_Save_Success
                                                , obj.Key);
                }
                return Json(rst);
            }
        }

        //
        // POST: /FMM/ScheduleMonth/Delete
        [HttpPost]
        public async Task<ActionResult> Delete(string locationName,string routeOperationName,string year,string month)
        {
            MethodReturnResult result = new MethodReturnResult();
            using (ScheduleMonthServiceClient client = new ScheduleMonthServiceClient())
            {
                ScheduleMonthKey key=new ScheduleMonthKey()
                {
                    LocationName = locationName,
                    RouteOperationName = routeOperationName,
                    Year = year,
                    Month = month
                };
                result = await client.DeleteAsync(key);
                if (result.Code == 0)
                {
                    result.Message = string.Format(FMMResources.StringResource.ScheduleMonth_Delete_Success
                                                   ,key);
                }
                return Json(result);
            }
        }
    }
}

jnmmes/ServiceCenter.Client/ServiceCenter.Client.Cell.Mvc/Areas/FMM/Views/ScheduleMonth/Index.cshtml
@model ServiceCenter.Client.Mvc.Areas.FMM.Models.ScheduleMonthQueryViewModel
@using ServiceCenter.MES.Model.FMM;
@using ServiceCenter.Model;
@using ServiceCenter.Common;
@using ServiceCenter.Client.Mvc.Areas.FMM.Models;
@using FMM=ServiceCenter.Client.Mvc.Resources.FMM;
@using ServiceCenter.Client.Mvc.Resources;

@{
    ViewBag.Title = FMM.StringResource.ScheduleMonth_ManagePageTitle;
    PagingConfig cfg = ViewBag.PagingConfig;

}
<h2>@ViewBag.Title</h2>

<div class="panel panel-default">
    <div class="panel-heading">
        <a href="javascript:showAddModal()" class="btn btn-primary">@StringResource.Add</a>
    </div>
    <div class="panel-body">
    @using (Ajax.BeginForm("Query", "ScheduleMonth", null
            , new AjaxOptions()
            {
                HttpMethod = "Post",
                OnBegin="beginQuery",
                UpdateTargetId = "list"
            }
            , new { @class = "form-horizontal", resource = "form" }))
    {
        @Html.AntiForgeryToken()
        <div class="row">
            <div class="col-md-1">
                @Html.LabelFor(m => m.LocationName, new { @class = "control-label" })
            </div>
            <div class="col-md-2">
                @Html.DropDownListFor(m => m.LocationName
                                    ,@Model.GetLocationName()
                                    ,string.Empty
                                    , new { @class = "form-control" })
            </div>
            <div class="col-md-1">
                @Html.LabelFor(m => m.RouteOperationName, new { @class = "control-label" })
            </div>
            <div class="col-md-2">
                @Html.DropDownListFor(m => m.RouteOperationName
                                    , @Model.GetRouteOperationName()
                                    , string.Empty
                                    , new { @class = "form-control" })
            </div>

            <div class="col-md-1">
                @Html.LabelFor(m => m.Year, new { @class = "control-label" })
            </div>
            <div class="col-md-1">
                @Html.TextBoxFor(m => m.Year, new { @class = "form-control" })
            </div>
            <div class="col-md-1">
                @Html.LabelFor(m => m.Month, new { @class = "control-label" })
            </div>
            <div class="col-md-1">
                @Html.TextBoxFor(m => m.Month, new { @class = "form-control" })
            </div>
            <div class="col-md-2">
                <input type="submit" value="@StringResource.Query" class="btn btn-default" />
            </div>
        </div>
    }
    </div>
    <div class="alert fade in hide" resource="alert" id="statusMessage" style="margin:0px">
        <button type="button" class="close" onclick="hideStatusMessage()">
            <span aria-hidden="true">×</span><span class="sr-only">Close</span>
        </button>
        <p></p>
    </div>
    <div id="list">
        @Html.Partial("_ListPartial",new ScheduleMonthViewModel())
    </div>
</div>

@*新增*@
<div id="add" class="modal fade" tabindex="-1" resource="dialog" aria-labelledby="addHeader" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true">&times;</span>
                <span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="addHeader">@FMM.StringResource.ScheduleMonth_AddTitle</h4>
            </div>
            <div class="modal-body" id="addContent" style="margin:0px;padding:5px">
                @using (Ajax.BeginForm("Save", "ScheduleMonth", null
                        , new AjaxOptions()
                        {
                            HttpMethod = "Post",
                            OnSuccess = "completeSave",
                            OnBegin = "beginSave"
                        }
                        , new { @class = "form-horizontal", resource = "form",id="frmAdd"}))
                {
                    @Html.AntiForgeryToken()
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <input type="submit" class="btn btn-primary" value="@StringResource.Save" id="btnSave" />
                            <input type="reset" class="btn btn-default" value="@StringResource.Reset" id="btnReset" />
                        </div>
                        <div class="panel-body">
                            <div class="alert fade in hide" resource="alert" id="addStatusMessage">
                                <button type="button" class="close" onclick="hideAddAlert()">
                                    <span aria-hidden="true">×</span><span class="sr-only">Close</span>
                                </button>
                                <p></p>
                            </div>
                            <div>
                                @Html.Partial("_AddPartial", new ScheduleMonthViewModel())
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts {


    <script type="text/javascript" language="javascript">
        //刷新列表
        function refreshList() {
            if ($("#frmPagingQuery").length > 0) {
                $("#frmPagingQuery").submit();
            }
        }
        //隐藏状态消息
        function hideStatusMessage() {
            $("#statusMessage").addClass("hide");
        }
    </script>
    @*查询*@
    <script type="text/javascript" language="javascript">
        //刷新列表
        function beginQuery() {
            hideStatusMessage();
        }
    </script>

    @*新增*@
    <script type="text/javascript" language="javascript">
        //保存
        $(function () {
            $('#add').on('hide.bs.modal', function (e) {
                $("#btnReset").click();
            });
            $("#add").on('shown.bs.modal', function (e) {
                var texts = $(this).find(":text:visible:enabled,:checkbox:visible:enabled,textarea:visible:enabled,select:visible:enabled");
                texts.eq(0).focus().select();
            });
        })

        function showAddModal() {
            hideAddAlert();
            hideStatusMessage();
            $("#btnSave").removeAttr("disabled");
            $('#add').modal('show');
        }

        function hideAddAlert() {
            $("#addStatusMessage").addClass("hide");
        }

        function beginSave() {
            $("#btnSave").attr("disabled", "disabled");
        }

        function completeSave(result) {
            $("#btnSave").removeAttr("disabled");
            $("#addStatusMessage").find("p").html(result.Message);
            $("#addStatusMessage").removeClass("hide");
            if (result.Code > 0) {
                $("#addStatusMessage").removeClass("alert-success");
                $("#addStatusMessage").addClass("alert-danger");
            }
            else {
                $("#addStatusMessage").removeClass("alert-danger");
                $("#addStatusMessage").addClass("alert-success");
                refreshList();
            }
        }
    </script>
    @*删除*@
    <script type="text/javascript" language="javascript">
        //删除资源
        function completeDelete(result) {
            $("#statusMessage").find("p").html(result.Message);
            $("#statusMessage").removeClass("hide");
            if (result.Code > 0) {
                $("#statusMessage").removeClass("alert-success");
                $("#statusMessage").addClass("alert-danger");
            }
            else {
                $("#statusMessage").removeClass("alert-danger");
                $("#statusMessage").addClass("alert-success");
                refreshList();
            }
        }
    </script>
}

jnmmes/ServiceCenter.Client/ServiceCenter.Client.Cell.Mvc/Areas/FMM/Views/ScheduleMonth/_ListPartial.cshtml
@model ServiceCenter.Client.Mvc.Areas.FMM.Models.ScheduleMonthViewModel
@using ServiceCenter.Client.Mvc.Areas.FMM.Models;
@using ServiceCenter.Client.Mvc.Resources;
@using FMM = ServiceCenter.Client.Mvc.Resources.FMM;
@using ServiceCenter.MES.Model.FMM;
@using ServiceCenter.Common;
@using ServiceCenter.Model;
@{
    PagingConfig cfg = ViewBag.PagingConfig;
}
<div id="_list">
    <table class="table table-hover table-bordered table-condensed">
        <thead>
            <tr class="active">
                <td>@StringResource.ItemNo</td>
                <td>@Html.DisplayNameFor(m => m.LocationName)</td>
                <td>@Html.DisplayNameFor(m => m.RouteOperationName)</td>
                <td>@Html.DisplayNameFor(m => m.Year)</td>
                <td>@Html.DisplayNameFor(m => m.Month)</td>
                <td>@StringResource.Detail</td>
                <td>@StringResource.Delete</td>
            </tr>
        </thead>
        @if (ViewBag.List != null)
        {
            <tbody>
                @for (int i = 0; i < ViewBag.List.Length; i++)
                {
                    ScheduleMonth obj = ViewBag.List[i];
                    <tr>
                        <td>@(cfg.PageSize * cfg.PageNo+i+1)</td>
                        <td>
                            @obj.Key.LocationName
                        </td>
                        <td>
                            @obj.Key.RouteOperationName
                        </td>
                        <td>
                            @obj.Key.Year
                        </td>
                        <td>
                            @obj.Key.Month
                        </td>
                        <td>
                            @Html.ActionLink(linkText: StringResource.Detail
                                            , actionName: "Index"
                                            , controllerName: "ScheduleDay"
                                            , routeValues: new {  @LocationName=obj.Key.LocationName,
                                                                  @RouteOperationName = obj.Key.RouteOperationName,
                                                                  @Year = obj.Key.Year,
                                                                  @Month = obj.Key.Month
                                                                }
                                            , htmlAttributes: new { @target = "_self" })
                        </td>
                        <td>
                            @Ajax.ActionLink(StringResource.Delete, actionName: null
                                            , routeValues: null
                                            , ajaxOptions:new AjaxOptions()
                                            {
                                                HttpMethod = "Post",
                                                Confirm = string.Format(FMM.StringResource.ScheduleMonth_ConfirmDelete, obj.Key),
                                                Url = Url.Action("Delete", new { @LocationName = obj.Key.LocationName,
                                                                                @RouteOperationName = obj.Key.RouteOperationName,
                                                                                @Year = obj.Key.Year,
                                                                                @Month = obj.Key.Month
                                                                               }),
                                                OnSuccess = "completeDelete"
                                            })
                        </td>
                    </tr>
                }
            </tbody>
        }
    </table>
    <div style="margin-top:-18px">
        @if (cfg != null)
        {
            using (Ajax.BeginForm("PagingQuery", "ScheduleMonth"
                            , new
                            {
                                @Where = cfg.Where,
                                @OrderBy = cfg.OrderBy,
                                @CurrentPageNo = cfg.PageNo,
                                @CurrentPageSize = cfg.PageSize
                            }
                            , new AjaxOptions()
                            {
                                HttpMethod = "Post",
                                UpdateTargetId = "_list"
                            }
                            , new { @class = "form-horizontal", resource = "form", id = "frmPagingQuery" }))
            {
                @Html.AntiForgeryToken()
                <div>@Html.Partial("_PaginationPartial")</div>
            }
        }
    </div>
</div>