jnmmes/ServiceCenter.Client/ServiceCenter.Client.Cell.Mvc/Areas/FMM/Models/MaterialViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using ServiceCenter.MES.Service.Client;
using ServiceCenter.Model;
using ServiceCenter.MES.Model.FMM;
using FMMResources = ServiceCenter.Client.Mvc.Resources.FMM;
using ServiceCenter.Client.Mvc.Resources;
using ServiceCenter.MES.Service.Client.FMM;
using System.Web.Mvc;
using ServiceCenter.Common;

namespace ServiceCenter.Client.Mvc.Areas.FMM.Models
{
    public class MaterialQueryViewModel
    {
        public MaterialQueryViewModel()
        {
        }

        [Display(Name = "MaterialQueryViewModel_Type", ResourceType = typeof(FMMResources.StringResource))]
        public string Type { get; set; }

        [Display(Name = "MaterialQueryViewModel_Code", ResourceType = typeof(FMMResources.StringResource))]
        public string Code { get; set; }

        [Display(Name = "MaterialQueryViewModel_Name", ResourceType = typeof(FMMResources.StringResource))]
        public string Name { get; set; }

    }

    public class MaterialViewModel
    {
        public MaterialViewModel()
        {
            this.CreateTime = DateTime.Now;
            this.EditTime = DateTime.Now;
            this.Status = EnumObjectStatus.Available;
        }

        [Required]
        [Display(Name = "MaterialViewModel_Code", ResourceType = typeof(FMMResources.StringResource))]
        [StringLength(50, MinimumLength = 2
                , ErrorMessageResourceName = "ValidateStringLength"
                , ErrorMessageResourceType = typeof(StringResource))]
        public string Code { get; set; }

        [Required]
        [Display(Name = "MaterialViewModel_Name", ResourceType = typeof(FMMResources.StringResource))]
        [StringLength(50, MinimumLength = 2
                        , ErrorMessageResourceName = "ValidateStringLength"
                        , ErrorMessageResourceType = typeof(StringResource))]
        public string Name { get; set; }


        [Display(Name = "MaterialViewModel_Spec", ResourceType = typeof(FMMResources.StringResource))]
        [StringLength(255, MinimumLength = 0, ErrorMessage = null
                   , ErrorMessageResourceName = "ValidateMaxStringLength"
                   , ErrorMessageResourceType = typeof(StringResource))]
        public string Spec { get; set; }

        [Display(Name = "MaterialViewModel_Unit", ResourceType = typeof(FMMResources.StringResource))]
        [StringLength(10, MinimumLength = 1
                , ErrorMessageResourceName = "ValidateStringLength"
                , ErrorMessageResourceType = typeof(StringResource))]
        public string Unit { get; set; }

        [Display(Name = "MaterialViewModel_BarCode", ResourceType = typeof(FMMResources.StringResource))]
        [StringLength(50, MinimumLength = 1
                , ErrorMessageResourceName = "ValidateStringLength"
                , ErrorMessageResourceType = typeof(StringResource))]
        public string BarCode { get; set; }

        [Display(Name = "MaterialViewModel_Type", ResourceType = typeof(FMMResources.StringResource))]
        public string Type { get; set; }

        [Display(Name = "MaterialViewModel_Class", ResourceType = typeof(FMMResources.StringResource))]
        [StringLength(50, MinimumLength = 1
                , ErrorMessageResourceName = "ValidateStringLength"
                , ErrorMessageResourceType = typeof(StringResource))]
        public string Class { get; set; }

        [Display(Name = "MaterialViewModel_IsRaw", ResourceType = typeof(FMMResources.StringResource))]
        public bool IsRaw { get; set; }

        [Display(Name = "MaterialViewModel_IsProduct", ResourceType = typeof(FMMResources.StringResource))]
        public bool IsProduct { get; set; }

        /// <summary>
        /// 每批主材料数量。
        /// </summary>
        [Required]
        [Display(Name = "MaterialTypeViewModel_MainRawQtyPerLot", ResourceType = typeof(FMMResources.StringResource))]
        public double MainRawQtyPerLot { get; set; }
        /// <summary>
        /// 每批产品数量。
        /// </summary>
        [Required]
        [Display(Name = "MaterialTypeViewModel_MainProductQtyPerLot", ResourceType = typeof(FMMResources.StringResource))]
        public double MainProductQtyPerLot { get; set; }

        [Display(Name = "Description", ResourceType = typeof(StringResource))]
        [StringLength(255, MinimumLength = 0, ErrorMessage = null
                     , ErrorMessageResourceName = "ValidateMaxStringLength"
                     , ErrorMessageResourceType = typeof(StringResource))]
        public string Description { get; set; }


        [Display(Name = "Status", ResourceType = typeof(StringResource))]
        public EnumObjectStatus Status { get; set; }

        [Display(Name = "Editor", ResourceType = typeof(StringResource))]
        public string Editor { get; set; }


        [Display(Name = "EditTime", ResourceType = typeof(StringResource))]
        public DateTime? EditTime { get; set; }


        [Display(Name = "Creator", ResourceType = typeof(StringResource))]
        public string Creator { get; set; }


        [Display(Name = "CreateTime", ResourceType = typeof(StringResource))]
        public DateTime? CreateTime { get; set; }


        public IEnumerable<SelectListItem> GetMaterialTypeList()
        {
            using (MaterialTypeServiceClient client = new MaterialTypeServiceClient())
            {
                PagingConfig cfg = new PagingConfig()
                {
                    IsPaging = false
                };

                MethodReturnResult<IList<MaterialType>> result = client.Get(ref cfg);
                if (result.Code <= 0)
                {
                    return from item in result.Data
                           select new SelectListItem()
                           {
                               Text = item.Key,
                               Value = item.Key
                           };
                }
            }
            return new List<SelectListItem>();
        }
        public IEnumerable<SelectListItem> GetObjectStatusList()
        {
            IDictionary<EnumObjectStatus, string> dic = EnumExtensions.GetDisplayNameDictionary<EnumObjectStatus>();

            return  from item in dic
                    select new SelectListItem()
                    {
                        Text = item.Value,
                        Value = Convert.ToString(item.Key)
                    };;
        }


    }
}

jnmmes/ServiceCenter.Client/ServiceCenter.Client.Cell.Mvc/Areas/FMM/Controllers/MaterialController.cs
using ServiceCenter.Client.Mvc.Areas.FMM.Models;
using FMMResources = ServiceCenter.Client.Mvc.Resources.FMM;
using ServiceCenter.MES.Model.FMM;
using ServiceCenter.MES.Service.Client.FMM;
using ServiceCenter.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ServiceCenter.Client.Mvc.Areas.FMM.Controllers
{
    public class MaterialController : Controller
    {
        //
        // GET: /FMM/Material/
        public async Task<ActionResult> Index()
        {
            using (MaterialServiceClient client = new MaterialServiceClient())
            {
                await Task.Run(() =>
                {
                    PagingConfig cfg = new PagingConfig()
                    {
                        OrderBy = "Key"
                    };
                    MethodReturnResult<IList<Material>> result = client.Get(ref cfg);

                    if (result.Code == 0)
                    {
                        ViewBag.PagingConfig = cfg;
                        ViewBag.List = result.Data;
                    }
                });
            }
            return View(new MaterialQueryViewModel());
        }

        //
        //POST: /FMM/Material/Query
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Query(MaterialQueryViewModel model)
        {
            if (ModelState.IsValid)
            {
                using (MaterialServiceClient client = new MaterialServiceClient())
                {
                    await Task.Run(() =>
                    {
                        StringBuilder where = new StringBuilder();
                        if (model != null)
                        {
                            if (!string.IsNullOrEmpty(model.Code))
                            {
                                where.AppendFormat(" {0} Key LIKE '{1}%'"
                                                    , where.Length > 0 ? "AND" : string.Empty
                                                    , model.Code);
                            }
                            if (!string.IsNullOrEmpty(model.Name))
                            {
                                where.AppendFormat(" {0} Name LIKE '{1}%'"
                                                    , where.Length > 0 ? "AND" : string.Empty
                                                    , model.Name);
                            }
                            if (!string.IsNullOrEmpty(model.Name))
                            {
                                where.AppendFormat(" {0} Type LIKE '{1}%'"
                                                    , where.Length > 0 ? "AND" : string.Empty
                                                    , model.Type);
                            }
                        }
                        PagingConfig cfg = new PagingConfig()
                        {
                            OrderBy = "Key",
                            Where = where.ToString()
                        };
                        MethodReturnResult<IList<Material>> result = client.Get(ref cfg);

                        if (result.Code == 0)
                        {
                            ViewBag.PagingConfig = cfg;
                            ViewBag.List = result.Data;
                        }
                    });
                }
            }
            return PartialView("_ListPartial");
        }
        //
        //POST: /FMM/Material/PagingQuery
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> PagingQuery(string where, string orderBy, int? currentPageNo, int? currentPageSize)
        {
            if (ModelState.IsValid)
            {
                int pageNo = currentPageNo ?? 0;
                int pageSize = currentPageSize ?? 20;
                if (Request["PageNo"] != null)
                {
                    pageNo = Convert.ToInt32(Request["PageNo"]);
                }
                if (Request["PageSize"] != null)
                {
                    pageSize = Convert.ToInt32(Request["PageSize"]);
                }

                using (MaterialServiceClient client = new MaterialServiceClient())
                {
                    await Task.Run(() =>
                    {
                        PagingConfig cfg = new PagingConfig()
                        {
                            PageNo = pageNo,
                            PageSize = pageSize,
                            Where = where ?? string.Empty,
                            OrderBy = orderBy ?? string.Empty
                        };
                        MethodReturnResult<IList<Material>> result = client.Get(ref cfg);
                        if (result.Code == 0)
                        {
                            ViewBag.PagingConfig = cfg;
                            ViewBag.List = result.Data;
                        }
                    });
                }
            }
            return PartialView("_ListPartial");
        }
        //
        // POST: /FMM/Material/Save
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Save(MaterialViewModel model)
        {
            using (MaterialServiceClient client = new MaterialServiceClient())
            {
                Material obj = new Material()
                {
                    Key = model.Code.ToUpper(),
                    BarCode=model.BarCode,
                    Name=model.Name,
                    Class=model.Class,
                    Spec=model.Spec,
                    Status=model.Status,
                    Type=model.Type,
                    Unit=model.Unit,
                    IsProduct=model.IsProduct,
                    IsRaw=model.IsRaw,
                    MainProductQtyPerLot=model.MainProductQtyPerLot,
                    MainRawQtyPerLot=model.MainRawQtyPerLot,
                    Description = model.Description,
                    Editor = User.Identity.Name,
                    EditTime = DateTime.Now,
                    CreateTime = DateTime.Now,
                    Creator = User.Identity.Name
                };
                MethodReturnResult rst = await client.AddAsync(obj);
                if (rst.Code == 0)
                {
                    rst.Message = string.Format(FMMResources.StringResource.Material_Save_Success
                                                , model.Code);
                }
                return Json(rst);
            }
        }
        //
        // GET: /FMM/Material/Modify
        public async Task<ActionResult> Modify(string key)
        {
            MaterialViewModel viewModel = new MaterialViewModel();
            using (MaterialServiceClient client = new MaterialServiceClient())
            {
                MethodReturnResult<Material> result = await client.GetAsync(key);
                if (result.Code == 0)
                {
                    viewModel = new MaterialViewModel()
                    {
                        Code=result.Data.Key,
                        BarCode=result.Data.BarCode,
                        Status=result.Data.Status,
                        Class=result.Data.Class,
                        Spec=result.Data.Spec,
                        Unit=result.Data.Unit,
                        MainRawQtyPerLot=result.Data.MainRawQtyPerLot,
                        MainProductQtyPerLot=result.Data.MainProductQtyPerLot,
                        Type=result.Data.Type,
                        Name = result.Data.Name,
                        IsProduct = result.Data.IsProduct,
                        IsRaw = result.Data.IsRaw,
                        CreateTime = result.Data.CreateTime,
                        Creator = result.Data.Creator,
                        Description = result.Data.Description,
                        Editor = result.Data.Editor,
                        EditTime = result.Data.EditTime
                    };
                    return PartialView("_ModifyPartial", viewModel);
                }
                else
                {
                    ModelState.AddModelError("", result.Message);
                }
            }
            return PartialView("_ModifyPartial");
        }

        //
        // POST: /FMM/Material/SaveModify
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SaveModify(MaterialViewModel model)
        {
            using (MaterialServiceClient client = new MaterialServiceClient())
            {
                MethodReturnResult<Material> result = await client.GetAsync(model.Code);

                if (result.Code == 0)
                {
                    result.Data.MainProductQtyPerLot = model.MainProductQtyPerLot;
                    result.Data.MainRawQtyPerLot = model.MainRawQtyPerLot;
                    result.Data.Name = model.Name;
                    result.Data.Spec=model.Spec;
                    result.Data.Class = model.Class;
                    result.Data.Status = model.Status;
                    result.Data.Type = model.Type;
                    result.Data.Unit = model.Unit;
                    result.Data.IsRaw = model.IsRaw;
                    result.Data.IsProduct = model.IsProduct;
                    result.Data.BarCode = model.BarCode;
                    result.Data.Description = model.Description;
                    result.Data.Editor = User.Identity.Name;
                    result.Data.EditTime = DateTime.Now;
                    MethodReturnResult rst = await client.ModifyAsync(result.Data);
                    if (rst.Code == 0)
                    {
                        rst.Message = string.Format(FMMResources.StringResource.Material_SaveModify_Success
                                                    , model.Code);
                    }

jnmmes/ServiceCenter.Client/ServiceCenter.Client.Cell.Mvc/Areas/FMM/Views/Material/Index.cshtml
@model ServiceCenter.Client.Mvc.Areas.FMM.Models.MaterialQueryViewModel
@using ServiceCenter.MES.Model.FMM;
@using ServiceCenter.Model;
@using ServiceCenter.Common;
@using ServiceCenter.Client.Mvc.Areas.FMM.Models;
@using FMM=ServiceCenter.Client.Mvc.Resources.FMM;
@using ServiceCenter.Client.Mvc.Resources;

@{
    ViewBag.Title = FMM.StringResource.Material_ManagePageTitle;
    PagingConfig cfg = ViewBag.PagingConfig;

}
<h2>@ViewBag.Title</h2>

<div class="panel panel-default">
    <div class="panel-heading">
        <a href="javascript:showAddModal()" class="btn btn-primary">@StringResource.Add</a>
    </div>
    <div class="panel-body ">
        @using (Ajax.BeginForm("Query", "Material", null
            , new AjaxOptions()
            {
                HttpMethod = "Post",
                OnBegin = "beginQuery",
                UpdateTargetId = "list"
            }
            , new { @class = "form-horizontal", resource = "form" }))
        {
            @Html.AntiForgeryToken()
            <div class="row">
                <div class="col-md-1">
                    @Html.LabelFor(m => m.Type, new { @class = "control-label" })
                </div>
                <div class="col-md-2">
                    @Html.TextBoxFor(m => m.Type, new { @class = "form-control" })
                </div>
                <div class="col-md-1">
                    @Html.LabelFor(m => m.Code, new { @class = "control-label" })
                </div>
                <div class="col-md-2">
                    @Html.TextBoxFor(m => m.Code, new { @class = "form-control" })
                </div>
                <div class="col-md-1">
                    @Html.LabelFor(m => m.Name, new { @class = "control-label" })
                </div>
                <div class="col-md-2">
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                </div>
                <div class="col-md-3">
                    <input type="submit" value="@StringResource.Query" class="btn btn-default" />
                </div>
            </div>
        }
    </div>
    <div class="alert fade in hide" resource="alert" id="statusMessage" style="margin:0px">
        <button type="button" class="close" onclick="hideStatusMessage()">
            <span aria-hidden="true">×</span><span class="sr-only">Close</span>
        </button>
        <p></p>
    </div>
    <div id="list">
        @Html.Partial("_ListPartial", new MaterialViewModel())
    </div>
</div>

@*新增*@
<div id="add" class="modal fade" tabindex="-1" resource="dialog" aria-labelledby="addHeader" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true">&times;</span>
                <span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="addHeader">@FMM.StringResource.Material_AddTitle</h4>
            </div>
            <div class="modal-body" id="addContent" style="margin:0px;padding:5px">
                @using (Ajax.BeginForm("Save", "Material", null
                        , new AjaxOptions()
                        {
                            HttpMethod = "Post",
                            OnSuccess = "completeSave",
                            OnBegin = "beginSave"
                        }
                        , new { @class = "form-horizontal", resource = "form",id="frmAdd"}))
                {
                    @Html.AntiForgeryToken()
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <input type="submit" class="btn btn-primary" value="@StringResource.Save" id="btnSave" />
                            <input type="reset" class="btn btn-default" value="@StringResource.Reset" id="btnReset" />
                        </div>
                        <div class="panel-body">
                            <div class="alert fade in hide" resource="alert" id="addStatusMessage">
                                <button type="button" class="close" onclick="hideAddAlert()">
                                    <span aria-hidden="true">×</span><span class="sr-only">Close</span>
                                </button>
                                <p></p>
                            </div>
                            <div>
                                @Html.Partial("_AddPartial", new MaterialViewModel())
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
@*显示明细*@
<div id="info"
     class="modal fade"
     tabindex="-1"
     resource="dialog"
     aria-labelledby="infoHeader"
     aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true">&times;</span>
                <span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="infoHeader">@FMM.StringResource.Material_DetailTitle</h4>
            </div>
            <div class="modal-body" id="infoContent" style="margin:0px;padding:5px">
                <form class="form-horizontal" resource="form">
                    <div class="panel panel-default">
                        <div class="panel-body" id="detailInfo">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@*修改*@
<div id="modify"
     class="modal fade"
     tabindex="-1"
     resource="dialog"
     aria-labelledby="modifyHeader"
     aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true">&times;</span>
                <span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="modifyHeader">@FMM.StringResource.Material_ModifyTitle</h4>
            </div>
            <div class="modal-body" id="modifyResourceContent" style="margin:0px;padding:5px">
                @using (Ajax.BeginForm("SaveModify", "Material", null
                    , new AjaxOptions()
                    {
                        HttpMethod = "Post",
                        OnSuccess = "completeSaveModify",
                        OnBegin = "beginSaveModify"
                    }
                    , new { @class = "form-horizontal", resource = "form" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <input type="submit" class="btn btn-primary" value="@StringResource.Save" id="btnSaveModify" />
                        </div>
                        <div class="panel-body">
                            <div class="alert fade in hide" resource="alert" id="modifyStatusMessage">
                                <button type="button" class="close" onclick="hideModifyAlert()">
                                    <span aria-hidden="true">×</span><span class="sr-only">Close</span>
                                </button>
                                <p></p>
                            </div>
                            <div id="modifyFormContent">
                                @Html.Partial("_ModifyPartial", new MaterialViewModel())
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts {


    <script type="text/javascript" language="javascript">
        //刷新列表
        function refreshList() {
            if ($("#frmPagingQuery").length > 0) {
                $("#frmPagingQuery").submit();
            }
        }
        //隐藏状态消息
        function hideStatusMessage() {
            $("#statusMessage").addClass("hide");
        }
    </script>
    @*查询*@
    <script type="text/javascript" language="javascript">
        //刷新列表
        function beginQuery() {
            hideStatusMessage();
        }
    </script>

    @*新增*@
    <script type="text/javascript" language="javascript">
        //保存
        $(function () {
            $('#add').on('hide.bs.modal', function (e) {
                $("#btnReset").click();
            });
            $("#add,#modify").on('shown.bs.modal', function (e) {
                var texts = $(this).find(":text:visible:enabled,:checkbox:visible:enabled,textarea:visible:enabled,select:visible:enabled");
                texts.eq(0).focus().select();
            });
        })

        function showAddModal() {
            hideAddAlert();
            hideStatusMessage();
            $("#btnSave").removeAttr("disabled");
            $('#add').modal('show');
        }

        function hideAddAlert() {
            $("#addStatusMessage").addClass("hide");
        }

        function beginSave() {
            $("#btnSave").attr("disabled", "disabled");
        }

        function completeSave(result) {
            $("#btnSave").removeAttr("disabled");
            $("#addStatusMessage").find("p").html(result.Message);
            $("#addStatusMessage").removeClass("hide");
            if (result.Code > 0) {
                $("#addStatusMessage").removeClass("alert-success");
                $("#addStatusMessage").addClass("alert-danger");
            }
            else {
                $("#addStatusMessage").removeClass("alert-danger");
                $("#addStatusMessage").addClass("alert-success");
                refreshList();
            }
        }
    </script>
    @*显示明细*@
    <script type="text/javascript" language="javascript">
        //显示明细
        function showInfoModal(result) {
            $('#info').modal('show')
        }
    </script>
    @*修改*@
    <script type="text/javascript" language="javascript">
        //修改资源
        function showModifyModal(result) {
            hideModifyAlert();
            hideStatusMessage();
            $("#btnSaveModify").removeAttr("disabled");
            $('#modify').modal('show')
        }

        function hideModifyAlert() {
            $("#modifyStatusMessage").addClass("hide");
        }

        function beginSaveModify() {
            $("#btnSaveModify").attr("disabled", "disabled");
        }

        function completeSaveModify(result) {
            $("#btnSaveModify").removeAttr("disabled");
            $("#modifyStatusMessage").find("p").html(result.Message);
            $("#modifyStatusMessage").removeClass("hide");
            if (result.Code > 0) {
                $("#modifyStatusMessage").removeClass("alert-success");
                $("#modifyStatusMessage").addClass("alert-danger");
            }
            else {
                $("#modifyStatusMessage").removeClass("alert-danger");
                $("#modifyStatusMessage").addClass("alert-success");
                refreshList();
            }
        }
    </script>
    @*删除*@
    <script type="text/javascript" language="javascript">
        //删除资源
        function completeDelete(result) {
            $("#statusMessage").find("p").html(result.Message);
            $("#statusMessage").removeClass("hide");
            if (result.Code > 0) {
                $("#statusMessage").removeClass("alert-success");
                $("#statusMessage").addClass("alert-danger");
            }
            else {
                $("#statusMessage").removeClass("alert-danger");
                $("#statusMessage").addClass("alert-success");
                refreshList();
            }
        }
    </script>
}