jnmmes/ServiceCenter.Client/ServiceCenter.Client.Module.Mvc/Areas/ZPVM/Models/ContrastColorViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ServiceCenter.Client.Mvc.Areas.ZPVM.Models
{
    public class ContrastColorViewModel
    {
        public ContrastColorViewModel()
        {
            this.StartTestTime = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1);
            this.EndTestTime = DateTime.Now.AddDays(1);
        }
        [Required]
        [Display(Name = "测试时间（起）")]
        public DateTime? StartTestTime { get; set; }
        [Required]
        [Display(Name = "测试时间（止）")]
        public DateTime? EndTestTime { get; set; }

    }
}

jnmmes/ServiceCenter.Client/ServiceCenter.Client.Module.Mvc/Areas/ZPVM/Controllers/ContrastColorController.cs
using ServiceCenter.Client.Mvc.Areas.ZPVM.Models;
using ServiceCenter.Model;
using ServiceCenter.Service.Client;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace ServiceCenter.Client.Mvc.Areas.ZPVM.Controllers
{
    public class ContrastColorController : Controller
    {
        //
        // GET: /ZPVM/ContrastColor/
        public ActionResult Index()
        {
            return View("Index", new ContrastColorViewModel());
        }

        public ActionResult Query(ContrastColorViewModel mode)
        {
            String countTotal = string.Format(@"select count(*) from dbo.v_LotColor where create_time>'{0}' and create_time<'{1}'", mode.StartTestTime, mode.EndTestTime);
            String countSame = string.Format(@"select count(*)  from dbo.v_LotColor where  Color=InspctResult and create_time>'{0}' and create_time<'{1}'", mode.StartTestTime, mode.EndTestTime);

            DataTable dtCountTotal = new DataTable();
            DataTable dtCountSame = new DataTable();
            String Proportion;
            using (DBServiceClient client = new DBServiceClient())
            {

                MethodReturnResult<DataTable> resultCountTotal = client.ExecuteQuery(countTotal);
                MethodReturnResult<DataTable> resultCountSame = client.ExecuteQuery(countSame);
                if (resultCountSame.Code == 0 && resultCountTotal.Code==0)
                {                 
                    dtCountSame = resultCountSame.Data;
                    dtCountTotal = resultCountTotal.Data;
                    Proportion = (Convert.ToDouble(dtCountSame.Rows[0][0]) / Convert.ToDouble(dtCountTotal.Rows[0][0])*100).ToString().Substring(0,4)+"%";
                    ViewBag.Proportion = Proportion;
                }
            }
            return PartialView("_ListPartial");
        }
	}
}

jnmmes/ServiceCenter.Client/ServiceCenter.Client.Module.Mvc/Areas/ZPVM/Views/ContrastColor/Index.cshtml
@model ServiceCenter.Client.Mvc.Areas.ZPVM.Models.ContrastColorViewModel
@using ServiceCenter.MES.Model.ZPVM;
@using ServiceCenter.Model;
@using ServiceCenter.Common;
@using ServiceCenter.Client.Mvc.Areas.ZPVM.Models;
@using ZPVMRsources = ServiceCenter.Client.Mvc.Resources.ZPVM;
@using ServiceCenter.Client.Mvc.Resources;

@{
    ViewBag.Title = "颜色匹配率查询";
}
<h2>@ViewBag.Title</h2>

        <div class="panel-body">
    @using (Ajax.BeginForm("Query", "ContrastColor", null
                , new AjaxOptions()
                 {
                     HttpMethod = "Post",
                     OnBegin = "beginQuery",
                     UpdateTargetId = "list",
                     OnComplete = "completeQuery"
                 }
                , new { @class = "form-horizontal", resource = "form", id = "frmQuery" }))
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            <div class="col-md-1">
                @Html.LabelFor(m => m.StartTestTime, new { @class = "control-label" })
            </div>
            <div class="col-md-2">
                @Html.TextBoxFor(m => m.StartTestTime, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.StartTestTime)
            </div>
            <div class="col-md-1">
                @Html.LabelFor(m => m.EndTestTime, new { @class = "control-label" })
            </div>
            <div class="col-md-2">
                @Html.TextBoxFor(m => m.EndTestTime, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.EndTestTime)
            </div>
            <div class="col-md-1">
                <input type="submit" value="@StringResource.Query" class="btn btn-primary" id="btnQuery" />
            </div>
        </div>

    }
</div>
    <div id="list" style="overflow:auto">
        @Html.Partial("_ListPartial")
    </div>

@section Scripts {
    @*查询*@
    <script type="text/javascript" language="javascript">
        //刷新列表
        function beginQuery(obj, req) {
            var data = $("#frmQuery").serialize();
            req.data += "&" + data;
            $("#btnQuery").attr("disabled", "disabled");
        }

        function completeQuery() {
            $("#btnQuery").removeAttr("disabled");
        }

        $(function () {
            $("#EndTestTime,#StartTestTime").datetimepicker({
                changeMonth: true,
                changeYear: true,
                dateFormat: "yy/mm/dd",
                timeFormat: 'HH:mm:ss'
            });
        });
    </script>
}

jnmmes/ServiceCenter.Client/ServiceCenter.Client.Module.Mvc/Areas/ZPVM/Views/ContrastColor/_ListPartial.cshtml
<div id="_list">
    <table class="table table-hover table-bordered table-condensed table-responsive table-striped">
        <thead>
            <tr class="active">
                <td nowrap>匹配率</td>
            </tr>
        </thead>

            <tbody>
                    <tr>
                       <td nowrap>@ViewBag.Proportion</td>
                   </tr>
            </tbody>
    </table>
</div>