jnmmes/ServiceCenter.Client/ServiceCenter.Client.Cell.Mvc/Areas/FMM/Models/ReasonCodeCategoryDetailViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using ServiceCenter.MES.Service.Client;
using ServiceCenter.Model;
using ServiceCenter.MES.Model.FMM;
using FMMResources = ServiceCenter.Client.Mvc.Resources.FMM;
using ServiceCenter.Client.Mvc.Resources;
using ServiceCenter.MES.Service.Client.FMM;
using System.Web.Mvc;
using ServiceCenter.Common;
using ServiceCenter.MES.Service.Client.BaseData;
using ServiceCenter.MES.Model.BaseData;

namespace ServiceCenter.Client.Mvc.Areas.FMM.Models
{
    public class ReasonCodeCategoryDetailQueryViewModel
    {
        public ReasonCodeCategoryDetailQueryViewModel()
        {

        }
        [Display(Name = "ReasonCodeCategoryDetailQueryViewModel_ReasonCodeCategoryName", ResourceType = typeof(FMMResources.StringResource))]
        public string ReasonCodeCategoryName { get; set; }

        [Display(Name = "ReasonCodeCategoryDetailQueryViewModel_ReasonCodeName", ResourceType = typeof(FMMResources.StringResource))]
        public string ReasonCodeName { get; set; }
    }

    public class ReasonCodeCategoryDetailViewModel
    {
        public ReasonCodeCategoryDetailViewModel()
        {
            this.EditTime = DateTime.Now;
            this.ItemNo = 1;
        }

        [Required]
        [Display(Name = "ReasonCodeCategoryDetailViewModel_ReasonCodeCategoryName", ResourceType = typeof(FMMResources.StringResource))]
        [StringLength(50, MinimumLength = 2
                        , ErrorMessageResourceName = "ValidateStringLength"
                        , ErrorMessageResourceType = typeof(StringResource))]
        public string ReasonCodeCategoryName { get; set; }

        [Required]
        [Display(Name = "ReasonCodeCategoryDetailViewModel_ReasonCodeName", ResourceType = typeof(FMMResources.StringResource))]
        public string ReasonCodeName { get; set; }

        [Required]
        [Display(Name = "ReasonCodeCategoryDetailViewModel_ItemNo", ResourceType = typeof(FMMResources.StringResource))]
        [Range(0, 65536
                , ErrorMessageResourceName = "ValidateRange"
                , ErrorMessageResourceType = typeof(StringResource))]
        [RegularExpression("[0-9]+"
                , ErrorMessageResourceName = "ValidateInt"
                , ErrorMessageResourceType = typeof(StringResource))]
        public int ItemNo { get; set; }


        [Display(Name = "Creator", ResourceType = typeof(StringResource))]
        public string Creator { get; set; }


        [Display(Name = "CreateTime", ResourceType = typeof(StringResource))]
        public DateTime? CreateTime { get; set; }

        [Display(Name = "Editor", ResourceType = typeof(StringResource))]
        public string Editor { get; set; }


        [Display(Name = "EditTime", ResourceType = typeof(StringResource))]
        public DateTime? EditTime { get; set; }

        public IEnumerable<SelectListItem> GetReasonCodeName(EnumReasonCodeType type)
        {
            using (ReasonCodeServiceClient client = new ReasonCodeServiceClient())
            {
                PagingConfig cfg = new PagingConfig()
                {
                    IsPaging = false,
                    Where = string.Format("Type='{0}'", Convert.ToInt32(type))
                };

                MethodReturnResult<IList<ReasonCode>> result = client.Get(ref cfg);
                if (result.Code <= 0)
                {
                    IEnumerable<SelectListItem> lst = from item in result.Data
                                                      select new SelectListItem()
                                                      {
                                                          Text = item.Key,
                                                          Value = item.Key
                                                      };
                    return lst;
                }
            }
            return new List<SelectListItem>();
        }
    }
}

jnmmes/ServiceCenter.Client/ServiceCenter.Client.Cell.Mvc/Areas/FMM/Controllers/ReasonCodeCategoryDetailController.cs
using ServiceCenter.Client.Mvc.Areas.FMM.Models;
using FMMResources = ServiceCenter.Client.Mvc.Resources.FMM;
using ServiceCenter.MES.Model.FMM;
using ServiceCenter.MES.Service.Client.FMM;
using ServiceCenter.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ServiceCenter.Client.Mvc.Areas.FMM.Controllers
{
    public class ReasonCodeCategoryDetailController : Controller
    {

        //
        // GET: /FMM/ReasonCodeCategoryDetail/
        public async Task<ActionResult> Index(string categoryName)
        {
            using (ReasonCodeCategoryServiceClient client = new ReasonCodeCategoryServiceClient())
            {
                MethodReturnResult<ReasonCodeCategory> result = await client.GetAsync(categoryName ?? string.Empty);
                if (result.Code > 0 || result.Data == null)
                {
                    return RedirectToAction("Index", "ReasonCodeCategory");
                }
                ViewBag.ReasonCodeCategory = result.Data;
            }

            using (ReasonCodeCategoryDetailServiceClient client = new ReasonCodeCategoryDetailServiceClient())
            {
                await Task.Run(() =>
                {
                    PagingConfig cfg = new PagingConfig()
                    {
                        OrderBy = "ItemNo",
                        Where = string.Format(" Key.ReasonCodeCategoryName = '{0}'"
                                                    , categoryName)
                    };
                    MethodReturnResult<IList<ReasonCodeCategoryDetail>> result = client.Get(ref cfg);

                    if (result.Code == 0)
                    {
                        ViewBag.PagingConfig = cfg;
                        ViewBag.List = result.Data;
                    }
                });
            }
            return View(new ReasonCodeCategoryDetailQueryViewModel() { ReasonCodeCategoryName = categoryName });
        }

        //
        //POST: /FMM/ReasonCodeCategoryDetail/Query
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Query(ReasonCodeCategoryDetailQueryViewModel model)
        {
            if (ModelState.IsValid)
            {
                using (ReasonCodeCategoryDetailServiceClient client = new ReasonCodeCategoryDetailServiceClient())
                {
                    await Task.Run(() =>
                    {
                        StringBuilder where = new StringBuilder();
                        if (model != null)
                        {
                            where.AppendFormat(" {0} Key.ReasonCodeCategoryName = '{1}'"
                                                    , where.Length > 0 ? "AND" : string.Empty
                                                    , model.ReasonCodeCategoryName);

                            if (!string.IsNullOrEmpty(model.ReasonCodeName))
                            {
                                where.AppendFormat(" {0} Key.ReasonCodeName LIKE '{1}%'"
                                                    , where.Length > 0 ? "AND" : string.Empty
                                                    , model.ReasonCodeName);
                            }
                        }
                        PagingConfig cfg = new PagingConfig()
                        {
                            OrderBy = "ItemNo",
                            Where = where.ToString()
                        };
                        MethodReturnResult<IList<ReasonCodeCategoryDetail>> result = client.Get(ref cfg);

                        if (result.Code == 0)
                        {
                            ViewBag.PagingConfig = cfg;
                            ViewBag.List = result.Data;
                        }
                    });
                }
            }
            return PartialView("_ListPartial");
        }
        //
        //POST: /FMM/ReasonCodeCategoryDetail/PagingQuery
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> PagingQuery(string where, string orderBy, int? currentPageNo, int? currentPageSize)
        {
            if (ModelState.IsValid)
            {
                int pageNo = currentPageNo ?? 0;
                int pageSize = currentPageSize ?? 20;
                if (Request["PageNo"] != null)
                {
                    pageNo = Convert.ToInt32(Request["PageNo"]);
                }
                if (Request["PageSize"] != null)
                {
                    pageSize = Convert.ToInt32(Request["PageSize"]);
                }

                using (ReasonCodeCategoryDetailServiceClient client = new ReasonCodeCategoryDetailServiceClient())
                {
                    await Task.Run(() =>
                    {
                        PagingConfig cfg = new PagingConfig()
                        {
                            PageNo = pageNo,
                            PageSize = pageSize,
                            Where = where ?? string.Empty,
                            OrderBy = orderBy ?? string.Empty
                        };
                        MethodReturnResult<IList<ReasonCodeCategoryDetail>> result = client.Get(ref cfg);
                        if (result.Code == 0)
                        {
                            ViewBag.PagingConfig = cfg;
                            ViewBag.List = result.Data;
                        }
                    });
                }
            }
            return PartialView("_ListPartial");
        }
        //
        // POST: /FMM/ReasonCodeCategoryDetail/Save
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Save(ReasonCodeCategoryDetailViewModel model)
        {
            using (ReasonCodeCategoryDetailServiceClient client = new ReasonCodeCategoryDetailServiceClient())
            {
                ReasonCodeCategoryDetail obj = new ReasonCodeCategoryDetail()
                {
                    Key = new ReasonCodeCategoryDetailKey() {
                        ReasonCodeCategoryName = model.ReasonCodeCategoryName,
                        ReasonCodeName = model.ReasonCodeName
                    },
                    ItemNo = model.ItemNo,
                    Editor = User.Identity.Name,
                    EditTime = DateTime.Now,
                    CreateTime=DateTime.Now,
                    Creator=User.Identity.Name
                };
                MethodReturnResult rst = await client.AddAsync(obj);
                if (rst.Code == 0)
                {
                    rst.Message = string.Format(FMMResources.StringResource.ReasonCodeCategoryDetail_Save_Success
                                                , obj.Key);
                }
                return Json(rst);
            }
        }
        //
        // GET: /FMM/ReasonCodeCategoryDetail/Modify
        public async Task<ActionResult> Modify(string categoryName,string reasonCodeName)
        {
            ReasonCodeCategoryDetailViewModel viewModel = new ReasonCodeCategoryDetailViewModel();
            using (ReasonCodeCategoryDetailServiceClient client = new ReasonCodeCategoryDetailServiceClient())
            {
                MethodReturnResult<ReasonCodeCategoryDetail> result = await client.GetAsync(new ReasonCodeCategoryDetailKey()
                {
                    ReasonCodeCategoryName=categoryName,
                    ReasonCodeName=reasonCodeName
                });
                if (result.Code == 0)
                {
                    viewModel = new ReasonCodeCategoryDetailViewModel()
                    {
                        ReasonCodeCategoryName = result.Data.Key.ReasonCodeCategoryName,
                        ReasonCodeName = result.Data.Key.ReasonCodeName,
                        ItemNo = result.Data.ItemNo,
                        Editor = result.Data.Editor,
                        EditTime = result.Data.EditTime,
                        CreateTime=result.Data.CreateTime,
                        Creator=result.Data.Creator
                    };
                    return PartialView("_ModifyPartial", viewModel);
                }
                else
                {
                    ModelState.AddModelError("", result.Message);
                }
            }
            return PartialView("_ModifyPartial");
        }

        //
        // POST: /FMM/ReasonCodeCategoryDetail/SaveModify
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SaveModify(ReasonCodeCategoryDetailViewModel model)
        {
            using (ReasonCodeCategoryDetailServiceClient client = new ReasonCodeCategoryDetailServiceClient())
            {
                MethodReturnResult<ReasonCodeCategoryDetail> result = await client.GetAsync(new ReasonCodeCategoryDetailKey()
                {
                    ReasonCodeCategoryName = model.ReasonCodeCategoryName,
                    ReasonCodeName = model.ReasonCodeName
                });

                if (result.Code == 0)
                {
                    result.Data.ItemNo = model.ItemNo;
                    result.Data.Editor = User.Identity.Name;
                    result.Data.EditTime = DateTime.Now;
                    MethodReturnResult rst = await client.ModifyAsync(result.Data);
                    if (rst.Code == 0)
                    {
                        rst.Message = string.Format(FMMResources.StringResource.ReasonCodeCategoryDetail_SaveModify_Success
                                                    , result.Data.Key);
                    }
                    return Json(rst);
                }
                return Json(result);
            }
        }
        //
        // GET: /FMM/ReasonCodeCategoryDetail/Detail
        public async Task<ActionResult> Detail(string categoryName, string reasonCodeName)

jnmmes/ServiceCenter.Client/ServiceCenter.Client.Cell.Mvc/Areas/FMM/Views/ReasonCodeCategoryDetail/Index.cshtml
@model ServiceCenter.Client.Mvc.Areas.FMM.Models.ReasonCodeCategoryDetailQueryViewModel
@using ServiceCenter.MES.Model.FMM;
@using ServiceCenter.Model;
@using ServiceCenter.Common;
@using ServiceCenter.Client.Mvc.Areas.FMM.Models;
@using FMM=ServiceCenter.Client.Mvc.Resources.FMM;
@using ServiceCenter.Client.Mvc.Resources;

@{
    ViewBag.Title = string.Format(FMM.StringResource.ReasonCodeCategoryDetail_ManagePageTitle, @Model.ReasonCodeCategoryName);
    PagingConfig cfg = ViewBag.PagingConfig;
    ReasonCodeCategory category = ViewBag.ReasonCodeCategory;
}
<h2>@ViewBag.Title</h2>
<h3>@category.Description</h3>
<div class="panel panel-default">
    <div class="panel-heading">
        <a href="javascript:showAddModal()" class="btn btn-primary">@StringResource.Add</a>
    </div>
    <div class="panel-body">
    @using (Ajax.BeginForm("Query", "ReasonCodeCategoryDetail", null
            , new AjaxOptions()
            {
                HttpMethod = "Post",
                OnBegin="beginQuery",
                UpdateTargetId = "list"
            }
            , new { @class = "form-horizontal", resource = "form" }))
    {
        @Html.AntiForgeryToken()
        <div class="row">
            <div class="col-md-1">
                @Html.LabelFor(m => m.ReasonCodeName, new { @class = "control-label" })
            </div>
            <div class="col-md-2">
                @Html.HiddenFor(m => m.ReasonCodeCategoryName)
                @Html.TextBoxFor(m => m.ReasonCodeName, new { @class = "form-control" })
            </div>
           
            <div class="col-md-9">
                <input type="submit" value="@StringResource.Query" class="btn btn-default" />
            </div>
        </div>
    }
    </div>
    <div class="alert fade in hide" resource="alert" id="statusMessage" style="margin:0px">
        <button type="button" class="close" onclick="hideStatusMessage()">
            <span aria-hidden="true">×</span><span class="sr-only">Close</span>
        </button>
        <p></p>
    </div>
    <div id="list">
        @Html.Partial("_ListPartial", new ReasonCodeCategoryDetailViewModel() 
                                           {  
                                               ReasonCodeCategoryName = @Model.ReasonCodeCategoryName
                                           })
    </div>
</div>

@*新增*@
<div id="add" class="modal fade" tabindex="-1" resource="dialog" aria-labelledby="addHeader" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true">&times;</span>
                <span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="addHeader">@FMM.StringResource.ReasonCodeCategoryDetail_AddTitle</h4>
            </div>
            <div class="modal-body" id="addContent" style="margin:0px;padding:5px">
                @using (Ajax.BeginForm("Save", "ReasonCodeCategoryDetail", null
                        , new AjaxOptions()
                        {
                            HttpMethod = "Post",
                            OnSuccess = "completeSave",
                            OnBegin = "beginSave"
                        }
                        , new { @class = "form-horizontal", resource = "form",id="frmAdd"}))
                {
                    @Html.AntiForgeryToken()
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <input type="submit" class="btn btn-primary" value="@StringResource.Save" id="btnSave" />
                            <input type="reset" class="btn btn-default" value="@StringResource.Reset" id="btnReset" />
                        </div>
                        <div class="panel-body">
                            <div class="alert fade in hide" resource="alert" id="addStatusMessage">
                                <button type="button" class="close" onclick="hideAddAlert()">
                                    <span aria-hidden="true">×</span><span class="sr-only">Close</span>
                                </button>
                                <p></p>
                            </div>
                            <div>
                                @Html.Partial("_AddPartial", new ReasonCodeCategoryDetailViewModel()
                                                               {
                                                                   ReasonCodeCategoryName = @Model.ReasonCodeCategoryName
                                                               })
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
@*显示明细*@
<div id="info"
     class="modal fade"
     tabindex="-1"
     resource="dialog"
     aria-labelledby="infoHeader"
     aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true">&times;</span>
                <span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="infoHeader">@FMM.StringResource.ReasonCodeCategoryDetail_DetailTitle</h4>
            </div>
            <div class="modal-body" id="infoContent" style="margin:0px;padding:5px">
                <form class="form-horizontal" resource="form">
                    <div class="panel panel-default">
                        <div class="panel-body" id="detailInfo">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@*修改*@
<div id="modify"
     class="modal fade"
     tabindex="-1"
     resource="dialog"
     aria-labelledby="modifyHeader"
     aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true">&times;</span>
                <span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="modifyHeader">@FMM.StringResource.ReasonCodeCategoryDetail_ModifyTitle</h4>
            </div>
            <div class="modal-body" id="modifyResourceContent" style="margin:0px;padding:5px">
                @using (Ajax.BeginForm("SaveModify", "ReasonCodeCategoryDetail", null
                    , new AjaxOptions()
                    {
                        HttpMethod = "Post",
                        OnSuccess = "completeSaveModify",
                        OnBegin = "beginSaveModify"
                    }
                    , new { @class = "form-horizontal", resource = "form" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <input type="submit" class="btn btn-primary" value="@StringResource.Save" id="btnSaveModify" />
                        </div>
                        <div class="panel-body">
                            <div class="alert fade in hide" resource="alert" id="modifyStatusMessage">
                                <button type="button" class="close" onclick="hideModifyAlert()">
                                    <span aria-hidden="true">×</span><span class="sr-only">Close</span>
                                </button>
                                <p></p>
                            </div>
                            <div id="modifyFormContent">
                                @Html.Partial("_ModifyPartial", new ReasonCodeCategoryDetailViewModel()
                                                               {
                                                                   ReasonCodeCategoryName = @Model.ReasonCodeCategoryName
                                                               })
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts {


    <script type="text/javascript" language="javascript">
        //刷新列表
        function refreshList() {
            if ($("#frmPagingQuery").length > 0) {
                $("#frmPagingQuery").submit();
            }
        }
        //隐藏状态消息
        function hideStatusMessage() {
            $("#statusMessage").addClass("hide");
        }
    </script>
    @*查询*@
    <script type="text/javascript" language="javascript">
        //刷新列表
        function beginQuery() {
            hideStatusMessage();
        }
    </script>

    @*新增*@
    <script type="text/javascript" language="javascript">
        //保存
        $(function () {
            $('#add').on('hide.bs.modal', function (e) {
                $("#btnReset").click();
            });
            $("#add,#modify").on('shown.bs.modal', function (e) {
                var texts = $(this).find(":text:visible:enabled,:checkbox:visible:enabled,textarea:visible:enabled,select:visible:enabled");
                texts.eq(0).focus().select();
            });
        })

        function showAddModal() {
            hideAddAlert();
            hideStatusMessage();
            $("#btnSave").removeAttr("disabled");
            $('#add').modal('show');
        }

        function hideAddAlert() {
            $("#addStatusMessage").addClass("hide");
        }

        function beginSave() {
            $("#btnSave").attr("disabled", "disabled");
        }

        function completeSave(result) {
            $("#btnSave").removeAttr("disabled");
            $("#addStatusMessage").find("p").html(result.Message);
            $("#addStatusMessage").removeClass("hide");
            if (result.Code > 0) {
                $("#addStatusMessage").removeClass("alert-success");
                $("#addStatusMessage").addClass("alert-danger");
            }
            else {
                $("#addStatusMessage").removeClass("alert-danger");
                $("#addStatusMessage").addClass("alert-success");
                refreshList();
            }
        }
    </script>
    @*显示明细*@
    <script type="text/javascript" language="javascript">
        //显示明细
        function showInfoModal(result) {
            $('#info').modal('show')
        }
    </script>
    @*修改*@
    <script type="text/javascript" language="javascript">
        //修改资源
        function showModifyModal(result) {
            hideModifyAlert();
            hideStatusMessage();
            $("#btnSaveModify").removeAttr("disabled");
            $('#modify').modal('show')
        }

        function hideModifyAlert() {
            $("#modifyStatusMessage").addClass("hide");
        }

        function beginSaveModify() {
            $("#btnSaveModify").attr("disabled", "disabled");
        }

        function completeSaveModify(result) {
            $("#btnSaveModify").removeAttr("disabled");
            $("#modifyStatusMessage").find("p").html(result.Message);
            $("#modifyStatusMessage").removeClass("hide");
            if (result.Code > 0) {
                $("#modifyStatusMessage").removeClass("alert-success");
                $("#modifyStatusMessage").addClass("alert-danger");
            }
            else {
                $("#modifyStatusMessage").removeClass("alert-danger");
                $("#modifyStatusMessage").addClass("alert-success");
                refreshList();
            }
        }
    </script>
    @*删除*@
    <script type="text/javascript" language="javascript">
        //删除资源
        function completeDelete(result) {
            $("#statusMessage").find("p").html(result.Message);
            $("#statusMessage").removeClass("hide");
            if (result.Code > 0) {
                $("#statusMessage").removeClass("alert-success");
                $("#statusMessage").addClass("alert-danger");
            }
            else {
                $("#statusMessage").removeClass("alert-danger");
                $("#statusMessage").addClass("alert-success");
                refreshList();
            }
        }
    </script>
}

jnmmes/ServiceCenter.Client/ServiceCenter.Client.Cell.Mvc/Areas/FMM/Views/ReasonCodeCategoryDetail/_ListPartial.cshtml
@model ServiceCenter.Client.Mvc.Areas.FMM.Models.ReasonCodeCategoryDetailViewModel
@using ServiceCenter.Client.Mvc.Areas.FMM.Models;
@using ServiceCenter.Client.Mvc.Resources;
@using FMM = ServiceCenter.Client.Mvc.Resources.FMM;
@using ServiceCenter.MES.Model.FMM;
@using ServiceCenter.Common;
@using ServiceCenter.Model;
@{
    PagingConfig cfg = ViewBag.PagingConfig;
}
<div id="_list">
    <table class="table table-hover table-bordered table-condensed">
        <thead>
            <tr class="active">
                <td>@Html.DisplayNameFor(m => m.ItemNo)</td>
                <td>@Html.DisplayNameFor(m => m.ReasonCodeName)</td>
                <td>@StringResource.Detail</td>
                <td>@StringResource.Modify</td>
                <td>@StringResource.Delete</td>
            </tr>
        </thead>
        @if (ViewBag.List != null)
        {
            <tbody>
                @for (int i = 0; i < ViewBag.List.Length; i++)
                {
                    ReasonCodeCategoryDetail obj = ViewBag.List[i];
                    <tr>
                        <td>@obj.ItemNo</td>
                        <td>
                            @obj.Key.ReasonCodeName
                        </td>
                        <td>
                            @Ajax.ActionLink(StringResource.Detail, actionName: null
                                            , routeValues: null
                                            , ajaxOptions:new AjaxOptions() 
                                            { 
                                                HttpMethod = "Post", 
                                                UpdateTargetId = "detailInfo",
                                                OnSuccess = "showInfoModal",
                                                Url = Url.Action("Detail", new { @CategoryName = obj.Key.ReasonCodeCategoryName, @ReasonCodeName = obj.Key.ReasonCodeName })
                                            })
                        </td>
                        <td>
                            @Ajax.ActionLink(StringResource.Modify, actionName: null
                                            ,routeValues:null
                                            ,ajaxOptions:new AjaxOptions()
                                            {
                                                HttpMethod = "Post",
                                                UpdateTargetId = "modifyFormContent",
                                                OnSuccess = "showModifyModal",
                                                Url = Url.Action("Modify", new { @CategoryName = obj.Key.ReasonCodeCategoryName, @ReasonCodeName = obj.Key.ReasonCodeName })
                                            })
                        </td>
                        <td>
                            @Ajax.ActionLink(StringResource.Delete, actionName: null
                                            , routeValues: null
                                            , ajaxOptions:new AjaxOptions()
                                            {
                                                HttpMethod = "Post",
                                                Confirm = string.Format(FMM.StringResource.ReasonCodeCategoryDetail_ConfirmDelete, obj.Key),
                                                Url = Url.Action("Delete", new { @CategoryName = obj.Key.ReasonCodeCategoryName, @ReasonCodeName = obj.Key.ReasonCodeName }),
                                                OnSuccess = "completeDelete"
                                            })
                        </td>
                    </tr>
                }
            </tbody>
        }
    </table>
    <div style="margin-top:-18px">
        @if (cfg != null)
        {
            using (Ajax.BeginForm("PagingQuery", "ReasonCodeCategoryDetail"
                            , new
                            {
                                @Where = cfg.Where,
                                @OrderBy = cfg.OrderBy,
                                @CurrentPageNo = cfg.PageNo,
                                @CurrentPageSize = cfg.PageSize
                            }
                            , new AjaxOptions()
                            {
                                HttpMethod = "Post",
                                UpdateTargetId = "_list"
                            }
                            , new { @class = "form-horizontal", resource = "form", id = "frmPagingQuery" }))
            {
                @Html.AntiForgeryToken()
                <div>@Html.Partial("_PaginationPartial")</div>
            }
        }
    </div>
</div>